### ISSUE TITLE
Week 1 - Innovation: Primitives

### ISSUE THREAD

**Issue by shreya-ahujaa** [shreya-ahujaa/fastpages#3]
## Part 1: code.org
- Understand how to use code.org and using it to complement your learning on primitives
   - Up to Unit 5 on Object - Orientated Programming
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/89224064/187126589-68104b4b-7d39-4888-b996-b6571321c562.png">

## Part 2: Productive Blogging
- Create a [Jupyter Notebook(s) using IJava kernel ](https://shreya-ahujaa.github.io/fastpages/fastpages/notes/primitives/pbl/2022/08/28/primitive-pbl.html)
   - use it to capture key learning on Primitives    
- Create a [Jupyter Notebook using Bash ](https://shreya-ahujaa.github.io/fastpages/fastpages/notes/primitives/2022/08/26/bash-and-checks.html)
    - use it to show that you have all the key tools installed
    - this should also be a blog for your own personal memory
- Each student captures information  in Fastpages thinking
   - capture information that will grow to ten college board units 
   - how they will recognize something as PBL vs College Board (for every unit, there will be one page for [PBL and experimental coding](https://shreya-ahujaa.github.io/fastpages/fastpages/notes/primitives/pbl/2022/08/28/primitive-pbl.html) and one for [Collegeboard and TPT Notes](https://shreya-ahujaa.github.io/fastpages/fastpages/notes/primitives/2022/08/23/primitive-collegeboard.html))

**Comment by AadyaDaita** [comment]
- [ ] Seeing that you understand how to use Code.org and that you used it to complement your learning on primitives.  Up to Lesson 5 in the OOP assignment.
- [ ] Productive Blogging
  - [ ]   Create a Jupyter Notebook(s) using IJava kernel and that you could use it to capture key learning on Primitives.   
  - [ ]   Create a Jupyter Notebook using Bash and that you could use it to show that you have all the key tools installed.   This should also be a Blog for your own personal memory.
  - [ ]   Each student captures information  in Fastpages thinking ... how they are going to capture information that will grow to 10 college board units ... how they will recognize something as PBL vs College Board.
